-- SimBlog17API schema bootstrap script
-- Target DB: PostgreSQL

-- 1) Create database (run as superuser or a role with CREATEDB privilege)
CREATE DATABASE simpleblog;

-- 2) Connect to target database (psql command)
\connect simpleblog;

-- 3) Core tables

CREATE TABLE IF NOT EXISTS users (
	id BIGSERIAL PRIMARY KEY,
	username VARCHAR(255) NOT NULL UNIQUE,
	avatar_url VARCHAR(512),
	password VARCHAR(255),
	role VARCHAR(16) NOT NULL DEFAULT 'USER',
	create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT ck_users_role CHECK (role IN ('USER', 'ADMIN'))
);

CREATE TABLE IF NOT EXISTS articles (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	title VARCHAR(255) NOT NULL,
	content TEXT NOT NULL,
	content_type VARCHAR(20) NOT NULL,
	preview TEXT,
	author_id BIGINT NOT NULL,
	published_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	view_count INTEGER,
	tags VARCHAR(255),
	status INTEGER NOT NULL,
	CONSTRAINT ck_articles_content_type CHECK (content_type IN ('PLAIN_TEXT', 'MARKDOWN', 'HTML')),
	CONSTRAINT ck_articles_status CHECK (status BETWEEN 0 AND 5),
	CONSTRAINT fk_articles_author FOREIGN KEY (author_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS comments (
	id BIGSERIAL PRIMARY KEY,
	article_id BIGINT NOT NULL,
	author_id BIGINT NOT NULL,
	parent_comment_id BIGINT,
	content VARCHAR(2000) NOT NULL,
	create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	status INTEGER NOT NULL DEFAULT 0,
	CONSTRAINT ck_comments_status CHECK (status BETWEEN 0 AND 3),
	CONSTRAINT fk_comments_author FOREIGN KEY (author_id) REFERENCES users (id),
	CONSTRAINT fk_comments_parent FOREIGN KEY (parent_comment_id) REFERENCES comments (id)
);

CREATE TABLE IF NOT EXISTS article_likes (
	id BIGSERIAL PRIMARY KEY,
	article_id BIGINT NOT NULL,
	user_id BIGINT NOT NULL,
	create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT uc_article_like_article_user UNIQUE (article_id, user_id),
	CONSTRAINT fk_article_likes_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS article_favorites (
	id BIGSERIAL PRIMARY KEY,
	article_id BIGINT NOT NULL,
	user_id BIGINT NOT NULL,
	create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT uc_article_fav_article_user UNIQUE (article_id, user_id),
	CONSTRAINT fk_article_favorites_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS media_assets (
	id BIGSERIAL PRIMARY KEY,
	uploader_id BIGINT NOT NULL,
	original_file_name VARCHAR(255) NOT NULL,
	stored_file_name VARCHAR(255) NOT NULL UNIQUE,
	content_type VARCHAR(100) NOT NULL,
	size_bytes BIGINT NOT NULL,
	file_url VARCHAR(512) NOT NULL,
	create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT fk_media_assets_uploader FOREIGN KEY (uploader_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS notifications (
	id BIGSERIAL PRIMARY KEY,
	user_id BIGINT NOT NULL,
	type VARCHAR(64) NOT NULL,
	target_type VARCHAR(32) NOT NULL,
	target_id BIGINT NOT NULL,
	title VARCHAR(128) NOT NULL,
	message VARCHAR(1000) NOT NULL,
	status INTEGER NOT NULL DEFAULT 0,
	create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	read_time TIMESTAMP,
	CONSTRAINT ck_notifications_status CHECK (status IN (0, 1)),
	CONSTRAINT fk_notifications_user FOREIGN KEY (user_id) REFERENCES users (id)
);

-- 4) Query-oriented indexes

CREATE INDEX IF NOT EXISTS idx_users_username ON users (username);
CREATE INDEX IF NOT EXISTS idx_users_username_lower ON users ((LOWER(username)));

CREATE INDEX IF NOT EXISTS idx_articles_status_published_time ON articles (status, published_time DESC);
CREATE INDEX IF NOT EXISTS idx_articles_author_status ON articles (author_id, status);
CREATE INDEX IF NOT EXISTS idx_articles_status_view_published ON articles (status, view_count DESC, published_time DESC);

CREATE INDEX IF NOT EXISTS idx_comments_article_status_time ON comments (article_id, status, create_time ASC);
CREATE INDEX IF NOT EXISTS idx_comments_status_time ON comments (status, create_time DESC);
CREATE INDEX IF NOT EXISTS idx_comments_author ON comments (author_id);

CREATE INDEX IF NOT EXISTS idx_article_likes_article ON article_likes (article_id);
CREATE INDEX IF NOT EXISTS idx_article_likes_user_time ON article_likes (user_id, create_time DESC);

CREATE INDEX IF NOT EXISTS idx_article_favorites_article ON article_favorites (article_id);
CREATE INDEX IF NOT EXISTS idx_article_favorites_user_time ON article_favorites (user_id, create_time DESC);

CREATE INDEX IF NOT EXISTS idx_media_assets_create_time ON media_assets (create_time);

CREATE INDEX IF NOT EXISTS idx_notifications_user_time ON notifications (user_id, create_time DESC);
CREATE INDEX IF NOT EXISTS idx_notifications_user_status ON notifications (user_id, status);




